name: hello world

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  hello-world-job:
    name: Say hello
    runs-on: ubuntu-latest

    steps:
      # checkout branch
      - name: checkout
        uses: actions/checkout@v2

      # do a greeting
      - name: hello world action step
        id: hello
        uses: ./
        with:
          who-to-greet: ${{ secrets.WHO_TO_GREET }}

      # do something with output
      - name: get output from step
        run: echo "Greeting happened to ${{ steps.hello.outputs.who-was-greeted }} at ${{ steps.hello.outputs.time }}"

      # do an upload
      - run: for l in `echo ${{ secrets.WHO_TO_GREET }}`; do echo $l >> name.txt; done
      - uses: actions/upload-artifact@v1
        with:
          name: name
          path: name.txt

  display-job:
    name: Display the results
    needs: hello-world-job
    runs-on: ubuntu-latest

    steps:
      - name: Download name
        uses: actions/download-artifact@v1
        with:
          name: name
      - name: Print the name
        shell: bash
        run: |
          value=`cat name/name.txt`
          echo The result is $value
