name: hello world

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    steps:
      # checkout branch
      - name: checkout
        uses: actions/checkout@v2

      # do a greeting
      - name: hello world action step
        id: hello
        uses: ./
        with:
          who-to-greet: ${{ secrets.WHO_TO_GREET }}

      # do something with output
      - name: get output from step
        run: echo "Greeting happened to ${{ steps.hello.outputs.who-was-greeted }} at ${{ steps.hello.outputs.time }}"
